/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {useEffect} from "react"
import {useSession, signIn, signOut} from "next-auth/react"

const Home: NextPage = () => {
  const {data: session, status} = useSession()
  useEffect(() => {
    if (session) {
      console.log(session)
    }
  }, [status])
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          session ? (
            <button onClick={() => signOut()}>Logout</button>
            ) : (
            <button onClick={() => signIn()}>Login</button>
          )
        }
      </main>
    </>
  );
};

export default Home;
